### ISSUE TITLE
"Show Context" option does not change context

### ISSUE THREAD

**Issue by dwhieb** [UAlbertaALTLab/korp-frontend#18]
The "Show Context" option does not change the context. It should switch between sentence context and paragraph context (I think).

**Current Behavior:**
![image](https://user-images.githubusercontent.com/5892997/107399668-388c9580-6abe-11eb-9e11-2bddacd25536.png)

**Desired Behavior:**
![image](https://user-images.githubusercontent.com/5892997/107399863-77225000-6abe-11eb-93a6-4265db753244.png)

**Comment by dwhieb** [comment]
@aarppe It looks like this feature is actually working. Can you clear your cache or try an incognito browser and try again on https://korp.altlab.dev?

**Comment by aarppe** [comment]
@dwhieb Yeah, using incognito/private browsing the full context option appeared to work.

**Comment by dwhieb** [comment]
Great! Closing this issue, will reopen if the problem resurfaces.
